name: Build Release Artifact

env:
  VERSION: 0.0.0

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Version
        run: cat VERSION >> $VERSION
      - name: Create Artifact
        run: zip artifact.zip code/*.py
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact.zip
          tag_name: v${{ env.VERSION }}
          name: Version ${{ env.VERSION }}
