name: Build Release Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest
    env:
      version: 0.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Version
        run: cat VERSION >> $version
      - name: Create Artifact
        run: zip artifact.zip code/*.py
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact.zip
          tag_name: v${{ env.version }}
          name: Version ${{ env.version }}
